### ISSUE TITLE
VerifyError: JNI sees Object instead of Try Monad

### ISSUE THREAD

**Issue by micotom** [arrow-kt/arrow#1227]
With switching from Try.Failure<T> to Try.Failure<Nothing> by default (PR: #971 ), a strange issue pops up:

`
fun causesVerifyError(): Try<Boolean> =
    try {
        val r = probablyFails()
        Try.Success(r)
            .map {
                !it
            }
    } catch (e: Exception) {
        Try.Failure(e)
    }
`

causes

`
java.lang.VerifyError: Bad return type
Exception Details:
  Location:
    MainKt.causesVerifyError()Larrow/core/Try; @110: areturn
  Reason:
    Type 'java/lang/Object' (current frame, stack[0]) is not assignable to 'arrow/core/Try' (from method signature)
  Current Frame:
    bci: @110
    flags: { }
    locals: { 'java/lang/Object', 'java/lang/Object' }
    stack: { 'java/lang/Object' }
  Bytecode:
    0x0000000: 00b8 0024 3bbb 0026 591a b800 2cb7 0030
    0x0000010: 4c00 2b4d 2c4e 2dc1 0032 9900 072c a700
    0x0000020: 392c b600 363a 0419 04c0 0028 b600 3936
    0x0000030: 0515 059a 0007 04a7 0004 03b8 002c 3a0e
    0x0000040: 190e 3a0f bb00 2659 190f b700 30c0 003b
    0x0000050: 3a07 1907 c000 3d00 004b a700 134c bb00
    0x0000060: 3259 2bc0 003f b700 42c0 003d 4b2a b0  
  Exception Handler Table:
    bci [0, 90] => handler: 93
  Stackmap Table:
    full_frame(@33,{Integer,Object[#38],Object[#38],Object[#38]},{})
    append_frame(@58,Object[#4],Integer)
    same_locals_1_stack_item_frame(@59,Integer)
    full_frame(@87,{Integer,Object[#38],Object[#38],Object[#38]},{Object[#4]})
    full_frame(@93,{},{Object[#32]})
    append_frame(@109,Object[#4],Object[#4])

	at java.lang.Class.getDeclaredMethods0(Native Method)
	at java.lang.Class.privateGetDeclaredMethods(Class.java:2701)
	at java.lang.Class.privateGetMethodRecursive(Class.java:3048)
	at java.lang.Class.getMethod0(Class.java:3018)
	at java.lang.Class.getMethod(Class.java:1784)
	at sun.launcher.LauncherHelper.validateMainClass(LauncherHelper.java:544)
	at sun.launcher.LauncherHelper.checkAndLoadMain(LauncherHelper.java:526)
Error: A JNI error has occurred, please check your installation and try again
`

Whereas following workaround works:

`
fun causesVerifyError(): Try<Boolean> =
    try {
        with(probablyFails()) {
            Try.Success(this)
                .map {
                    !it
                }
        }
    } catch (e: Exception) {
        Try.Failure(e)
    }
 `

**Kotlin version**: 1.3.11
**JDK Target**: 1.8
**JDK**: 1.8.0_181

**Comment by veiset** [comment]
It looks like you are defining a very weird type (`:` instead of `=`). Did you mean to write:

```
fun causesVerifyError(): Try<Boolean> = Try<Boolean> {
    val b = someBooleanFunction()
    return Try.Success(b)
        .map {
            !it
        }
}
```

**Comment by raulraja** [comment]
I wonder what happens if the `Either` functions are not `inline`. This seems a bug possibly related to the bytecode emitted.

**Comment by veiset** [comment]
You're right. My bad. Getting the same error here too.

**Comment by raulraja** [comment]
@micotom can you provide a complete example that includes exactly the imports you are using?

**Comment by raulraja** [comment]
This works for me:
```kotlin
object test {
  fun someBooleanFunction(): Boolean = true
  fun causesVerifyError(): Try<Boolean> {
    val b = someBooleanFunction()
    return Try.Success(b)
      .map {
        !it
      }
  }
  @JvmStatic
  fun main(args: Array<String>) {
    println(causesVerifyError())
  }
}
```
Output:
```
/Library/Java/JavaVirtualMachines/jdk1.8.0_172.jdk/Contents/Home/bin/java "-javaagent:/Applications/IntelliJ IDEA CE.app/Contents/lib/idea_rt.jar=61936:/Applications/IntelliJ IDEA CE.app/Contents/bin" -...

Success(value=false)

Process finished with exit code 0
```

**Comment by micotom** [comment]
I collected some more info on the issue:

- It is not only bound to `Try`, but at least also to `Option` in their according `map`, hence probably to any functor in the lib
- A method failing with the bytecode error does not even need to be called but just be initialized somewhere in the code (see example below)
- Using the identify function to generate an instance does work, using the constructor causes the bytecode error

**Example**

Executing the main method here will already make the program fail although no function has been called.
If we remove `f1()`, the program just executes fine. Also calling `f2()` then works as expected.

````kotlin
import arrow.core.Option
import arrow.core.Some

fun f1() = Some(5).map { it }

fun f2() = Option.just(5).map { it }

fun main(args: Array<String>) {}
````

**Environment**: Arrow 0.8.2 / Kotlin 1.3.11 / Project SDK Java 1.8.0_181

**Comment by pakoito** [comment]
This seems localized to your setup, else we'd have more reports of this problem, right? Are you doing anything interesting in the build.gradle? Can you repro it in a new project on a new machine?

**Comment by raulraja** [comment]
is it possible that you have mixed versions of arrow in the classpath of the project where that is running?

**Comment by micotom** [comment]
@pakoito veiset (see [conversation](https://github.com/arrow-kt/arrow/issues/1227#issuecomment-451135234) above) could reproduce the issue. I will try to find some time to set it up also on another machine and report back.

Gradle build file is super basic. I'm always checking back the errors in a plain Intellij project. So (@raulraja ) also the classpath is clean, arrow versions all point to one def in the build file.

And just checked again: The error only pops up from Arrow version 0.7.3 and above.

**Comment by alissonfpmorais** [comment]
I've created a basic datatype replicating `Try` and get the same error.
Two things that fixed the problem was: getting rid of `inline` modifier or refactor to old implementation as @micotom pointed out. 

Differences from 0.8.2 and 0.7.2:

```
// 0.8.2
inline fun <B> map(f: (A) -> B): Try<B> =
    flatMap { Success(f(it)) }

// 0.7.2
// This works
inline fun <B> map(crossinline f: (A) -> B): Try<B> =
    fold({ Failure(it) }, { Success(f(it)) })

// Another possible solution, but has performance penaulty
fun <B> map(f: (A) -> B): Try<B> =
    flatMap { Success(f(it)) }
```

**Comment by pakoito** [comment]
So...an inliner bug maybe? Worth checking in the kotlinlang slack with someone from jetbrains.

**Comment by alissonfpmorais** [comment]
I've made some more tests to better understand the issue and I end up with this tiny piece of code:

```
// Does not work
fun main(args: Array<String>) {
    println(causesVerifyErrorSample())
}

fun causesVerifyErrorSample(): Sample<Boolean> {
    return Sample.Success(true)
        .flatMap {
            Sample.Failure(RuntimeException(""))
        }
}

sealed class Sample<out T> {
    inline fun <R> flatMap(f: (T) -> Sample<R>): Sample<R> =
        when (this) {
            is Failure -> this
            is Success -> f(this.value)
        }

    data class Failure(val exception: Throwable): Sample<Nothing>()
    data class Success<out T>(val value: T): Sample<T>()
}
```

This code does not work!
To make it work, I've made one small change in `flatMap`:

```
// From
inline fun <R> flatMap(f: (T) -> Sample<R>): Sample<R> =
    when (this) {
        is Failure -> this
        is Success -> f(this.value)
    }

// To
inline fun <R> flatMap(f: (T) -> Sample<R>): Sample<R> =
    when (this) {
        is Success -> f(this.value)
        is Failure -> this
    }
```

Then I started to play with code and found that:
1) Commenting `println(causesVerifyErrorSample())` does not affect if code works or not
2) Leaving uncommented just `sealed class Sample<out T> { /* code here */ }` does not throw any error
3) Error just pop up when function `causesVerifyErrorSample` is uncommented, method `flatMap` is `inlined` and `Failure`/`Sample<Nothing>` is the top clause of `when` (even if it has more than 2 clauses)

Some differences between two versions of `causesVerifyErrorSample`, when looking the decompiled code:
```
// This works
@NotNull
public static final Sample causesVerifyErrorSample() {
   Sample this_$iv = new Success(true);
   boolean it = (Boolean)this_$iv.getValue();
   return (Sample)(new Failure((Throwable)(new RuntimeException(""))));
}

// This does not work
@NotNull
public static final Sample causesVerifyErrorSample() {
   Sample this_$iv = new Success(true);
   Object var10000; // Possible root error?
   if (this_$iv instanceof Failure) {
      var10000 = this_$iv;
   } else {
      boolean it = (Boolean)this_$iv.getValue();
      var10000 = (Sample)(new Failure((Throwable)(new RuntimeException(""))));
   }

   return (Sample)var10000;
}
```

So... after this odyssey, I'm not entirely sure about root cause, but possible solution is not mix `inline` and generic type `Nothing` (as top conditional clause). If someone can check these results too, would be appreciated :+1: 
Meanwhile I'll start a refactor to address this issue.

**Comment by micotom** [comment]
@alissonfpmorais Confirmed from my side (also with my own `Option` reimplementation): If the clause with `<T>` and not the one with `Nothing` is at top of the clause, your example works.

However, something like:
```kotlin
fun causesSampleVerifyError2() = Sample.Failure(IllegalArgumentException()).map {
    it
}

// given map is implemented in Sample as:
inline fun <R> map(f: (T) -> R): Sample<R> = flatMap {
    Success(f(it))
}
```
will then still fail.

**Comment by pakoito** [comment]
Definitely something that Jetbrains will be excited about 🗡 

@alissonfpmorais thank you for getting minimal repro, you should report it to https://youtrack.jetbrains.com/issues/KT and link it here so we can +1 it

**Comment by alissonfpmorais** [comment]
@micotom nice catch, I haven't done this test!
@pakoito I hope that they enjoy work on it :smile:
I'm going to report it tonight and I'll link here :+1: 
What would be the approach in this case? Refactor to old implementation or wait for Jetbrains's fix?

**Comment by pakoito** [comment]
I'd say wait for the fix, use functions meanwhile.

**Comment by alissonfpmorais** [comment]
> I'd say wait for the fix, use functions meanwhile.

@pakoito Okey dokey :)


Here is the [issue](https://youtrack.jetbrains.com/issue/KT-29242).
If I left something, feel free to tell me and I'll fix it.
