### ISSUE TITLE
["Request"] Calculations on `Duration.INFINITE` should not overflow

### ISSUE THREAD

**Issue by supersven** [arrow-kt/arrow#1796]
## What version are you currently using?

Latest master

## What would you like to see?

Calculations like `times` and `plus` on `Duration.INFINITE` should not overflow. Because this issue is due to calculations based on `Long`, it is not limited to `Duration.INFINITE`, but here the case is most obvious.

Additionally, it would be nice if `nanoseconds` would always be "valid" for the given `amount`. I.e. currently a large `amount` leads to `Long.MAX_VALUE` in `nanoseconds`, where a larger `nanoseconds` value would be right.

## Example

Currently
```
    "INFINITE plus one should be INFINITE" {
        val d = Duration(1L, TimeUnit.NANOSECONDS)
        Duration.INFINITE.plus(d).nanoseconds shouldBe  Duration.INFINITE.nanoseconds
    }
```
results in
```
expected: 9223372036854775807L but was: -9223372036854775808L
org.opentest4j.AssertionFailedError: expected: 9223372036854775807L but was: -9223372036854775808L
	at arrow.fx.data.DurationTest$3.invokeSuspend(DurationTest.kt:32)
	at arrow.fx.data.DurationTest$3.invoke(DurationTest.kt)
	at io.kotlintest.runner.jvm.TestCaseExecutor$executeTest$supervisorJob$1$invokeSuspend$$inlined$map$lambda$1.invokeSuspend(TestCaseExecutor.kt:130)
	at kotlin.coroutines.jvm.internal.BaseContinuationImpl.resumeWith(ContinuationImpl.kt:33)
	at kotlinx.coroutines.DispatchedTask.run(Dispatched.kt:241)
	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1149)
	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:624)
	at java.lang.Thread.run(Thread.java:748)
```

**Comment by nomisRev** [comment]
Thanks for the bug report @supersven!

I've been thinking we should Deprecate Arrow Fx's Duration in favor of the [Duration](https://kotlinlang.org/api/latest/jvm/stdlib/kotlin.time/-duration/index.html) type now included into the std.

**Comment by supersven** [comment]
Thanks for the quick respose, @nomisRev !

Using Kotlin's own `Duration` sounds like a good idea:

1. It's based on IEEE 754 `Double`s, that have a notion of infinity. (I think there are some strange corner cases*, but people should be used to them as it's the standard...)
1. Closer to Kotlin's stdlib means less friction in the usage of other libraries.

--
*) IEEE 754 floating points are always good for a surprise ... 😉

**Comment by nomisRev** [comment]
@supersven We've implemented this here #2025, but as mentioned in the PR it still seems very experimental. Any idea? The impl looks like what you'd expect from a `Duration` type, not sure how much this could be subject to change.

**Comment by supersven** [comment]
Hey @nomisRev ,

Thanks for getting me involved. As #2025 is closed due to `Duration` being still experimental, I would wait till it's "production ready", too. :smiley: 

Please feel free to ping me, if there's a new PR.
