### ISSUE TITLE
["Request"] Λrrow Analysis Kotlin 1.7.20 support

### ISSUE THREAD

**Issue by nacyolsa** [arrow-kt/arrow#2844]
What version are you currently using?
Λrrow Analysis 2.0.2

What would you like to see?
Does Λrrow Analysis support Kotlin 1.7.20? I'm receiving OutOfMemoryError after a few minutes of compilation.

```
java.lang.OutOfMemoryError: Java heap space
	at java.base/java.util.HashMap.resize(HashMap.java:700)
	at java.base/java.util.HashMap.putVal(HashMap.java:659)
	at java.base/java.util.HashMap.put(HashMap.java:608)
	at de.uni_freiburg.informatik.ultimate.util.datastructures.ScopedHashMap.put(ScopedHashMap.java:305)
	at de.uni_freiburg.informatik.ultimate.logic.Theory.defineFunction(Theory.java:1470)
	at de.uni_freiburg.informatik.ultimate.logic.Theory.defineFunction(Theory.java:1511)
	at de.uni_freiburg.informatik.ultimate.logic.NoopScript.defineFunInternal(NoopScript.java:283)
	at de.uni_freiburg.informatik.ultimate.logic.NoopScript.annotate(NoopScript.java:507)
	at org.sosy_lab.java_smt.solvers.smtinterpol.SmtInterpolTheoremProver.addConstraint(SmtInterpolTheoremProver.java:43)
	at org.sosy_lab.java_smt.solvers.smtinterpol.SmtInterpolTheoremProver.addConstraint(SmtInterpolTheoremProver.java:25)
	at org.sosy_lab.java_smt.basicimpl.withAssumptionsWrapper.BasicProverWithAssumptionsWrapper.addConstraint(BasicProverWithAssumptionsWrapper.java:48)
	at arrow.meta.plugins.analysis.phases.analysis.solver.state.SolverState.addConstraint(SolverState.kt:83)
	at arrow.meta.plugins.analysis.phases.analysis.solver.state.SolverState.newName(SolverState.kt:106)
	at arrow.meta.plugins.analysis.phases.analysis.solver.check.ExpressionsKt.checkRegularFunctionCall(Expressions.kt:562)
	at arrow.meta.plugins.analysis.phases.analysis.solver.check.ExpressionsKt.checkCallExpression(Expressions.kt:425)
	at arrow.meta.plugins.analysis.phases.analysis.solver.check.ExpressionsKt.fallThrough(Expressions.kt:259)
	at arrow.meta.plugins.analysis.phases.analysis.solver.check.ExpressionsKt.access$fallThrough(Expressions.kt:1)
	at arrow.meta.plugins.analysis.phases.analysis.solver.check.ExpressionsKt$checkExpressionConstraints$2.invoke(Expressions.kt:243)
	at arrow.meta.plugins.analysis.phases.analysis.solver.check.ExpressionsKt$checkExpressionConstraints$2.invoke(Expressions.kt:156)
	at arrow.meta.continuations.ContSeq$flatMap$1.invokeSuspend(ContSeq.kt:60)
	at kotlin.coroutines.jvm.internal.BaseContinuationImpl.resumeWith(ContinuationImpl.kt:33)
	at arrow.meta.continuations.ContSeqBuilder.hasNext(ContSeq.kt:233)
	at arrow.meta.continuations.ContSeq$map$1.invokeSuspend(ContSeq.kt:292)
	at kotlin.coroutines.jvm.internal.BaseContinuationImpl.resumeWith(ContinuationImpl.kt:33)
	at arrow.meta.continuations.ContSeqBuilder.hasNext(ContSeq.kt:233)
	at arrow.meta.continuations.ContSeq$flatMap$1.invokeSuspend(ContSeq.kt:292)
	at kotlin.coroutines.jvm.internal.BaseContinuationImpl.resumeWith(ContinuationImpl.kt:33)
	at arrow.meta.continuations.ContSeqBuilder.hasNext(ContSeq.kt:233)
	at arrow.meta.continuations.ContSeqBuilder.yieldAll(ContSeq.kt:274)
	at arrow.meta.continuations.ContSeqSyntax$DefaultImpls.yieldAll(ContSeq.kt:165)
	at arrow.meta.continuations.ContSeqBuilder.yieldAll(ContSeq.kt:203)
	at arrow.meta.continuations.ContSeq$flatMap$1.invokeSuspend(ContSeq.kt:60)

```

**Comment by fathom-piotr** [comment]
For me no support for newer Kotlin version manifests as:
```
java.lang.NoSuchMethodError: 'void org.jetbrains.kotlin.ir.expressions.impl.IrConstructorCallImpl.<init>(int, int, org.jetbrains.kotlin.ir.types.IrType, org.jetbrains.kotlin.ir.symbols.IrConstructorSymbol, int, int, int, org.jetbrains.kotlin.ir.expressions.IrStatementOrigin, int, kotlin.jvm.internal.DefaultConstructorMarker)'
	at arrow.meta.phases.codegen.ir.IrUtils.irConstructorCall(IrUtils.kt:140)
...
```

Related thread: https://kotlinlang.slack.com/archives/C5UPMM0A0/p1667556569737689

**Comment by nomisRev** [comment]
Arrow Analysis lives on a separate project, https://github.com/arrow-kt/arrow-analysis. I think it would be useful to open the ticket there.

**Comment by nacyolsa** [comment]
New ticket [arrow-analysis](https://github.com/arrow-kt/arrow-analysis)](https://github.com/arrow-kt/arrow-analysis/issues/52) this one can be closed.
