### ISSUE TITLE
[BUG] Arrow result continuation broken

### ISSUE THREAD

**Issue by ulfryk** [arrow-kt/arrow#2875]
**Affected version:** `1.1.2`
**Affected scope:** `arrow.core.continuations`
**Kotlin version:** `1.7.21`

Using `result { … }` comprehension and binding invokations of suspended functions/methods inside causes unexpected behaviour. Nested `Result<Result<X>>` values are returned in runtime - despite having `Result<X>` type in compile time.

Bug affects `result { … }` and `result.eager { … }`.
It does NOT affect `nullable { … }` / `nullable.eager { … }` or `either { … }` / `either.eager { … }`.

Code to reproduce an issue:

```kotlin
import arrow.core.continuations.result
import kotlinx.coroutines.delay

suspend fun main() {
    val ok = result { "whatever" }
    println("The OK Result is: $ok")

    val a = getV()
    println("The A Result is: $a")

    val b = result {
        delay(1)
        "whatever"
    }
    println("The B Result is: $b")

    val c = result {
        getV().bind()
    }
    println("The C Result is: $c")

    val d = result {
        val v = getV().bind()

        v + "__cont"
    }
    println("The D Result is: $d")

}

private suspend fun getV() = result {
    delay(1)
    "whatever"
}
```

Result of running above code:

```
The OK Result is: Success(whatever)
The A Result is: Success(Success(whatever))
The B Result is: Success(Success(whatever))
The C Result is: Success(Success(Success(whatever)))
Exception in thread "main" java.lang.ClassCastException: class kotlin.Result cannot be cast to class java.lang.String (kotlin.Result is in unnamed module of loader 'app'; java.lang.String is in module java.base of loader 'bootstrap')
	at com.fiatrepublic.pomerania.oauth2server.pkceimpl.EffectsIssueKt$main$$inlined$invoke-gIAlu-s$4$3.invokeSuspend(Effect.kt:0)
	at kotlin.coroutines.jvm.internal.BaseContinuationImpl.resumeWith(ContinuationImpl.kt:33)
	at arrow.core.continuations.FoldContinuation.resumeWith(Effect.kt:713)
	at kotlin.coroutines.jvm.internal.BaseContinuationImpl.resumeWith(ContinuationImpl.kt:46)
	at kotlinx.coroutines.DispatchedTaskKt.resume(DispatchedTask.kt:178)
	at kotlinx.coroutines.DispatchedTaskKt.dispatch(DispatchedTask.kt:166)
	at kotlinx.coroutines.CancellableContinuationImpl.dispatchResume(CancellableContinuationImpl.kt:397)
	at kotlinx.coroutines.CancellableContinuationImpl.resumeImpl(CancellableContinuationImpl.kt:431)
	at kotlinx.coroutines.CancellableContinuationImpl.resumeImpl$default(CancellableContinuationImpl.kt:420)
	at kotlinx.coroutines.CancellableContinuationImpl.resumeUndispatched(CancellableContinuationImpl.kt:518)
	at kotlinx.coroutines.EventLoopImplBase$DelayedResumeTask.run(EventLoop.common.kt:500)
	at kotlinx.coroutines.EventLoopImplBase.processNextEvent(EventLoop.common.kt:284)
	at kotlinx.coroutines.DefaultExecutor.run(DefaultExecutor.kt:108)
	at java.base/java.lang.Thread.run(Thread.java:830)

Process finished with exit code 1
```

**Comment by nomisRev** [comment]
Hey @ulfryk,

Thank you for the bug report, including reproducible examples.
I saw you mentioned `Affected version: 1.1.2`, is this also reproducible in `1.1.3` and/or `1.1.4-rc.3`?

**Comment by ulfryk** [comment]
Hey @nomisRev,

Checked other versions `1.1.3` has same issue but `1.1.4-rc.3` seems to have it fixed 🎉 :

### 1.1.3
```
The OK Result is: Success(whatever)
The A Result is: Success(Success(whatever))
The B Result is: Success(Success(whatever))
The C Result is: Success(Success(Success(whatever)))
Exception in thread "main" java.lang.ClassCastException: class kotlin.Result cannot be cast to class java.lang.String (kotlin.Result is in unnamed module of loader 'app'; java.lang.String is in module java.base of loader 'bootstrap')
	at com.fiatrepublic.pomerania.oauth2server.pkceimpl.ArrowIssuesKt$main$$inlined$invoke-gIAlu-s$4.invokeSuspend(result.kt:0)
	at kotlin.coroutines.jvm.internal.BaseContinuationImpl.resumeWith(ContinuationImpl.kt:33)
	at arrow.core.continuations.FoldContinuation.resumeWith(Effect.kt:756)
	at kotlin.coroutines.jvm.internal.BaseContinuationImpl.resumeWith(ContinuationImpl.kt:46)
	at kotlinx.coroutines.DispatchedTaskKt.resume(DispatchedTask.kt:178)
	at kotlinx.coroutines.DispatchedTaskKt.dispatch(DispatchedTask.kt:166)
	at kotlinx.coroutines.CancellableContinuationImpl.dispatchResume(CancellableContinuationImpl.kt:397)
	at kotlinx.coroutines.CancellableContinuationImpl.resumeImpl(CancellableContinuationImpl.kt:431)
	at kotlinx.coroutines.CancellableContinuationImpl.resumeImpl$default(CancellableContinuationImpl.kt:420)
	at kotlinx.coroutines.CancellableContinuationImpl.resumeUndispatched(CancellableContinuationImpl.kt:518)
	at kotlinx.coroutines.EventLoopImplBase$DelayedResumeTask.run(EventLoop.common.kt:500)
	at kotlinx.coroutines.EventLoopImplBase.processNextEvent(EventLoop.common.kt:284)
	at kotlinx.coroutines.DefaultExecutor.run(DefaultExecutor.kt:108)
	at java.base/java.lang.Thread.run(Thread.java:830)

Process finished with exit code 1
```

### 1.1.4-4c.3
```
The OK Result is: Success(whatever)
The A Result is: Success(whatever)
The B Result is: Success(whatever)
The C Result is: Success(whatever)
The D Result is: Success(whatever__cont)

Process finished with exit code 0
```

**Comment by nomisRev** [comment]
@ulfryk thanks for letting us know ☺️ We're currently rolling out 1.1.4, and will be released this week.
Will close this issue after it's officially released.

**Comment by nomisRev** [comment]
This fix has been released ☺️ Closing the issue.
