### ISSUE TITLE
NoClassDefFoundError on Kotlin 1.2.41

### ISSUE THREAD

**Issue by iirekm** [arrow-kt/arrow#859]
```
e: [kapt] An exception occurred: java.lang.NoClassDefFoundError: org/jetbrains/kotlin/serialization/jvm/JvmProtoBufUtil
	at me.eugeniomarletti.kotlin.metadata.KotlinClassMetadata$data$2.invoke(KotlinMetadata.kt:51)
	at me.eugeniomarletti.kotlin.metadata.KotlinClassMetadata$data$2.invoke(KotlinMetadata.kt:50)
	at kotlin.SynchronizedLazyImpl.getValue(Lazy.kt:131)
	at me.eugeniomarletti.kotlin.metadata.KotlinClassMetadata.getData(KotlinMetadata.kt)
	at arrow.optics.OptikalProcessor.evalAnnotatedElement(OpticsProcessor.kt:74)
	at arrow.optics.OptikalProcessor.onProcess(OpticsProcessor.kt:38)
	at arrow.common.utils.AbstractProcessor.process(AbstractProcessor.kt:20)
	at org.jetbrains.kotlin.kapt3.ProcessorWrapper.process(annotationProcessing.kt:131)
	at com.sun.tools.javac.processing.JavacProcessingEnvironment.callProcessor(JavacProcessingEnvironment.java:794)
	at com.sun.tools.javac.processing.JavacProcessingEnvironment.discoverAndRunProcs(JavacProcessingEnvironment.java:70
```

**Comment by iirekm** [comment]
now this class seems to be in package org.jetbrains.kotlin.metadata.jvm.deserialization

**Comment by pakoito** [comment]
We probably need to release a new version to fix this :) Ping @raulraja @JorgeCastilloPrz @nomisRev this weekend?

**Comment by JorgeCastilloPrz** [comment]
Definitely. Wasn't it already fixed on current `master` branch? (potential 0.7.2). I think @Takhion has the clues on where's the problem.

**Comment by Takhion** [comment]
It was fixed in #821 and yeah apparently it's not released yet 😁

**Comment by JorgeCastilloPrz** [comment]
I'd love to wait for #860 and #856 if possible. I want to give those types a try along with `FlowableK` and `ObservableK` in a client project.

**Comment by JorgeCastilloPrz** [comment]
Yeah I'll work on it today most likely.

**Comment by JorgeCastilloPrz** [comment]
`SingleK` and `MaybeK` are already in so I don't need anything else from my side. Can we proceed on releasing? How are released done? Anything special to do other than tagging master? (Was it automatized @Guardiola31337?)

**Comment by dgoetsch** [comment]
I was able to temporarily get a round t his by setting my project kotlin  version to `1.2.31`, seems to be caused by  something other than arrow. I didn't see this issue until I added kapt as a gradle plugin AND added annotations to generate higherkinds or optics.

The exemplar in this bug ticket includes the kapt plugin, but  I didn't see a dependency  on arrow:
https://youtrack.jetbrains.com/oauth?state=%2Fissue%2FKT-23902

**Comment by Takhion** [comment]
@dgoetsch have you tried [this](https://github.com/Takhion/kotlin-metadata/issues/8#issuecomment-385331329)?

**Comment by Takhion** [comment]
@dgoetsch the problem is that `kotlin-metadata` is not just being used by arrow, but also by other libraries (like Room)

**Comment by IgorGanapolsky** [comment]
Setting Kotlin to version 1.2.31 has no effect on this error

**Comment by pakoito** [comment]
@IgorGanapolsky have you updated to Arrow 0.7.2?

**Comment by IgorGanapolsky** [comment]
@pakoito The strange thing is I'm not even using Arrow in my project.  Still getting this error...

**Comment by pakoito** [comment]
...


what

**Comment by pakoito** [comment]
Update Eugenio's kotlin-metadata, or update any transitive libraries that use it. Check with gradle deps or another similar subcommand.

**Comment by IgorGanapolsky** [comment]
@pakoito There is no kotlin-metadata in my project whatsoever

**Comment by pakoito** [comment]
Happy to hear that solved it. It's a weird issue indeed.

**Comment by Takhion** [comment]
related: https://github.com/Takhion/kotlin-metadata/issues/8#issuecomment-409517076
